### ISSUE TITLE
Crucible bug

### ISSUE THREAD

**Issue by Mrthomas20121** [TFC-Metallum/TFCTech#11]
The TFCTech Crucible does not correct to power cable blocking it from getting power.

**Comment by Roonas** [comment]
@Mrthomas20121 are you sure you're trying to feed power into the correct side? It needs to be the face with the red and yellow square. [It works just fine on my end.](https://cdn.discordapp.com/attachments/400504502551052288/647194738855903232/unknown.png)

**Comment by Mrthomas20121** [comment]
that could be the case, i'll test it
