### ISSUE TITLE
Add compatibility to other mods energy net (IC2, GTCE)

### ISSUE THREAD

**Issue by UnlimatedStone9** [TFC-Metallum/TFCTech#17]
That's it really, power consumption from other mods power types would be ideal.

**Comment by DisasterMoo** [comment]
finished adding compatibility to both mods e-net:
https://github.com/TFC-Metallum/TFCTech/commit/184ecc01ed0342bd9b873631f58a11ce4337bc54
https://github.com/TFC-Metallum/TFCTech/commit/903bffc9780e4407591e489bdec41cdfe12ddc55
