### ISSUE TITLE
Audio Related Crash on Server

### ISSUE THREAD

**Issue by Linc7991** [TFC-Metallum/TFCTech#22]
It seems placing or breaking either the electric forge or induction furnace causes a ISound error as well as crashing the server most times. From what I've seen online, it's related to something with referencing ISound in a class server's use.

[crash-2019-12-26_22.24.27-server.txt](https://github.com/TFC-Metallum/TFCTech/files/4004072/crash-2019-12-26_22.24.27-server.txt)

**Comment by KaneHart** [comment]
Also having this issue. Did not crash but can't break / interact was a bloody mess I even tried using like this on top of it and would not replace the block and created an error:

/setblock ~ ~-1 ~ dirt
