### ISSUE TITLE
[Bug] unable to open electric forge

### ISSUE THREAD

**Issue by Mrthomas20121** [TFC-Metallum/TFCTech#24]
i can't open the electric forge(the gui doesn't show up).
fortunately vanillafix is preventing me from crashing.
other tfctech blocks works fine.
crash report : https://paste.dimdev.org/kezuwaxari.mccrash
forge version : forge-14.23.5.2847
tfc version: 1.12.2-0.28.2.113
tfc tech version : 1.12-1.1.5

**Comment by Mrthomas20121** [comment]
my guess on the error is that a method was removed/moved and cause a crash because tfc tech can't find it as it doesn't exist.

**Comment by DisasterMoo** [comment]
Yeah, there was a change in `ContainerTE`  to fix mold sync issues, in turn i need to update to match.

**Comment by DisasterMoo** [comment]
Finally can close this: https://github.com/TFC-Metallum/TFCTech/releases/tag/v1.2.6
