### ISSUE TITLE
The recipe for glass block mold is identical to the recipe for large vessel.

### ISSUE THREAD

**Issue by AtomicBlastPony** [TFC-Metallum/TFCTech#42]
The recipe for glass block mold is identical to the recipe for unfired large vessel.
Did you even test this before release?..

**Comment by DisasterMoo** [comment]
> Did you even test this before release?..
I'm working all alone in these implementations (i do have help in textures tho). Do you really expect me to remember + test every little detail? Just look how big this last update is.

That said, I do test everything i can remember, just not by per detail basis (imagine loading the game just to test a single recipe when you have 100+ WIP stuff going).

Finally, thanks for the bug report.

**Comment by AtomicBlastPony** [comment]
Sorry if it sounded rude, didn't mean to imply you don't put effort in it. The mod is definitely great and had a lot of work put into it. Thanks for the quick response!
