### ISSUE TITLE
Can't place levers on induction crucible

### ISSUE THREAD

**Issue by Dragnier** [TFC-Metallum/TFCTech#60]
Your other powered blocks (Fridge and Forge) accept RF just fine from Redstone Minus Redstone (makes active redstone signals directly power blocks at a configurable rate per tick; basically you can just stick a lever on things or place redstone dust or blocks next to them to get RF when they are active). However, the Induction Crucible does not get powered from any face with powered redstone dust or redstone blocks and I cannot place a lever on the block on any side.

EDIT:
I take that back somewhat. It only accepts power from it's front face for some reason? Still can't attach a lever directly to it though.

**Comment by DisasterMoo** [comment]
The energy input behavior is working as intended, the induction crucible has only one face (the one with the dot) that accepts input.
