### ISSUE TITLE
Crashed while viewing brass casting recipes with the crucible.

### ISSUE THREAD

**Issue by wrachilles** [TFC-Metallum/TFCTech#65]
[crash-2020-08-03_15.48.09-client.txt](https://github.com/TFC-Metallum/TFCTech/files/5018458/crash-2020-08-03_15.48.09-client.txt)

**Comment by DisasterMoo** [comment]
This is related to https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/840 which only occurs on saves where you add / remove mods that registers fluids for the same metals TFC registers. There's no way to fix that besides deleting your map and generating a new one.
