### ISSUE TITLE
Crucible: some metals from other addons have higher melting point than Brilliant White 1601C.

### ISSUE THREAD

**Issue by cola98765** [TFC-Metallum/TFCTech#73]
Some metals have much higher melting point, up to 3400C, so while it is possible to work, and even melt them with Electric Forge, Induction Crucible is limited to 1601C in objects/tileentities/TEInductionCrucible.java line 138
`this.acceptHeat(Heat.maxVisibleTemperature());`
This calls tfc api, which answers with 1601.

Sugestions:
Simple:
Replace `Heat.maxVisibleTemperature()` with a config value
Pros: I can melt tungsten
Cons: I might need to wait forever for lead to cool down.

Complex:
Add same custom temp gauge as in Electric Forge.
Pros: I can melt anything with outputting liquid in preferable temperature.
Cons: It more complex

**Comment by DisasterMoo** [comment]
Definitely gonna do the complex, it's better to give off people a better gauge for custom temperatures now that base TFC is not hardcoded on `Heat.maxVisibleTemperature()`
