### ISSUE TITLE
Crafttweaker capability to add items as fuel for smeltery firebox

### ISSUE THREAD

**Issue by VoidFox57** [TFC-Metallum/TFCTech#74]
I am using TFC-Tech in a modpack that I am developing and vanilla coal as well as TFC logs are disabled. I am using Geolosys coals and would like to be able to use them as fuel in the smeltery firebox.. 

Enhancement

TFC-Tech Unofficial v. 1.2.15 for MC 1.12.2

**Comment by DisasterMoo** [comment]
There is one actually, forgot to mention it in wiki about it, sorry. The firebox accepts any `Fuel` registered in TFC's fuel system, so you can add more fuels there via `ItemRegistry.registerFuel`. 

More information: 
https://terrafirmacraft.github.io/Documentation/1.12.x/crafttweaker/items/
