### ISSUE TITLE
Ash crafting line is redundant

### ISSUE THREAD

**Issue by KittenRaee** [TFC-Metallum/TFCTech#76]
Vanilla TFC already has Wood Ash \<tfc:wood_ash\> obtained from campfires. Whole tech line behind ash feels redundant, If issue is renewability of wood ash, one could simply burn wooden things (eg. lumber pieces or bundles of stick) inside a forge to make wood ash instead of making whole new ash, which is redundantly based around wood processing.

**Comment by DisasterMoo** [comment]
TFCTech's Ash exists before TFC added one. I will see how to change that
