### ISSUE TITLE
crash on server start(water?)

### ISSUE THREAD

**Issue by aldo1028** [TFC-Metallum/TFCTech#9]
getting a server crash on startup with the following error logs

[crash-2019-09-23_21.17.34-server.txt](https://github.com/TFC-Metallum/TFCTech/files/3644797/crash-2019-09-23_21.17.34-server.txt)
[crash-2019-09-23_21.17.32-client.txt](https://github.com/TFC-Metallum/TFCTech/files/3644800/crash-2019-09-23_21.17.32-client.txt)

**Comment by aldo1028** [comment]
tried booting without nocubes and dynamic sounds, same issue still persist

**Comment by DisasterMoo** [comment]
Looks like something is odd with your compiler, per discord discusion.
